# -*- coding: utf-8 -*-
"""Assignment3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sgKcLOveyEzUg_jX_b8zigCu2OfcMwzE

Question 1: Rice Market Analysis (NumPy)
"""

import numpy as np

prices = np.array([1200, 1250, 1180, 1300, 1220, 1270, 1240])

# b) Mean price
mean_price = np.mean(prices)
print(f"Mean Price: {mean_price}")

# c) Highest and lowest
highest = np.max(prices)
lowest = np.min(prices)
print(f"Highest Price: {highest}")
print(f"Lowest Price: {lowest}")

# d) Difference
diff = highest - lowest
print(f"Difference: {diff}")

"""Question 2: Price Shock Investigation (NumPy)"""

new_prices = np.array([1200, 1250, 1180, 1300, 1220, 1270, 2000])

# a) Recalculate mean
new_mean = np.mean(new_prices)
# b) Comparison: The mean increases significantly because 2000 is an outlier.
# c) Explanation: Unusually high values (outliers) skew the mean, making it less
# representative of the typical daily price, which can mislead decision-making.
print(f"New Mean Price: {new_mean}")

# Calculate the median of the new prices
new_median = np.median(new_prices)
print(f"New Median Price: {new_median}")

# Comparison and Explanation
# The median (1250) is less affected by the outlier (2000) compared to the mean (1345.71).
# This demonstrates that the median is a more robust measure of central tendency for skewed distributions or data with outliers,
# as it represents the middle value regardless of extreme values.

"""Question 3: County Crop Survey (Pandas)"""

import pandas as pd

csv_url = 'https://raw.githubusercontent.com/marcushgrigsby39-web/Machine-Learning-with-python-Bootcamp./main/cassava_data.csv'

# a) Load the dataset from the URL
df = pd.read_csv(csv_url, on_bad_lines="skip")

# b) Display the first five rows
print(df.head())

# c) Print the number of rows and columns
print(f"Dataset has {df.shape[0]} rows and {df.shape[1]} columns.")

# d) Print the column names
print(f"Column names: {df.columns.tolist()}")

"""Question 4: Finding Areas with Low Production (Pandas)"""

# a) Counties with cassava_bags < 80
low_prod = df[df['cassava_bags'] < 80]
print(low_prod)
# b) Count
count = len(low_prod)
print(f"Number of counties with cassava_bags < 80: {count}")
# c) Explanation: This helps an agricultural officer identify regions that need
# interventions, such as better seeds, fertilizer, or training to improve yields.

"""Question 5: Visualizing School Attendance (Matplotlib)"""

import matplotlib.pyplot as plt

data = [35, 37, 40, 38, 42, 39, 41]
plt.plot(data, marker='o')
plt.title('School Attendance Trend')
plt.xlabel('Day')
plt.ylabel('Attendance')
plt.show()

# d) Trend: The graph shows a general upward fluctuation, indicating that attendance
# is relatively stable with minor daily variations.