# -*- coding: utf-8 -*-
"""Orientation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cz2DcdxLr7mp1KgCFHZAOjk1NX4ID5nr
"""



"""Example of Addition"""

A=2
B=3
C=A+B
print(C)

"""Example of string"""

Greetings= "whatsup with you, Dehtor."
print(Greetings)

"""Example of Addition

Example of String
"""

Greetings="Advice na,pror"
print(Greetings)